### PR TITLE
Updated plugin

### PR DESCRIPTION
**Pull request by kartsims**
Hey!

Thanks for the great plugin, it helped me a lot while migrating from WPEC to Woo :-)

I thought I would contribute since I had some stuff to do (like migrating orders as well), I hope you will like what you see and it will help others.

++
Simon

### CODE REVIEW

**Comment by codekipple** [comment]
Hey!

This is brilliant thanks!. I haven't actually used this code in over 2 years. So i would have to fire it up again and give your pull request ago. 

Your work will make this code much more relevant and useful to people tackling this problem at the moment.

Thanks i really appreciate the pull request. I'll try an get it merged in as soon as i can.

**Comment by kartsims** [comment]
Cool, glad you like it ! 

I guess it feels nice to have a pull request, especially on something you have written some time ago ! :)

FYI I have developped it last week and will go live with it in production in the next days.

Have a good day and let me know when you find time to merge it,

Simon

**Comment by ghost** [comment]
just used the updated plugin that kartsims had posted. Most things worked except the following:

> I had to change _order_currency to USD on line 915, else all orders were in Euro's.
> 
> For some reason the _price field on products was not being updated, so all products had a "Regular Price" but not an actual Price (and thus showing as Free). I think that is because the original _wpsc_special_price field contained a 0 rather than being empty (not sure if this is from an older version of wp-ecommerce?)  
> changed line 416:  
> </code>   if(   $sale_price != '0' && $sale_price != $regular_price){ </code>
>   this solved that problem for me
> 
> on the plugin page, where it says "WPEC Cart at a glance"  the counts are all shown as zero, except for Coupons and Processing. Possibly meta-tags need updating? 
> 
> when running the plugin, I was getting errors that said:
> Warning: in_array() expects parameter 2 to be array, boolean given in ../wpec-to-woo/wpec-to-woo.php on line 529....
> Edited line 529 to:       if ( $featured_products ) {
>  this got rid of the errors, but not sure if something does not migrate now, as my case does not use featured products

++++++++++++++
This is a really great plugin, and did everything I needed. Woocommerce has something like this but costs $30.00. Thanks for all the work

**Comment by codekipple** [comment]
Thanks @ghettocottage, i really need to have a look at this and get the code merged. Hopefully this weekend.

**Comment by kartsims** [comment]
Thanks for the review!

I actually work in France so that's where the EUR are from ;-)

Many code modifications like this one were very specific to our project, that's why we can't call this a proper plugin... Hopefully we'll get there if people keep getting involved such as you.

Cheers,

Simon

**Comment by ghost** [comment]
Wonderful! Let me know if you need testing. I have the database dump and can go back to original WPEC setup and migrate to WooCommerce as much as needed.

**Comment by kartsims** [comment]
@chrillep just sent a new pull request but you haven't merged mine yet...

**Comment by codekipple** [comment]
ok sorry about that, will pull my finger out.

**Comment by chrillep** [comment]
yeah i think all the != '' should be != null,
cause it keeps interpreting the the saleprice 0 as a string not null but ill keep trying

**Comment by codekipple** [comment]
I'll fire up the plugin this weekend and have a look at it. I don't actually use this code anymore it was a one time thing.

**Pull request merged**
